# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x0eproto_messages\"\x1e\n\x0bTestMessage\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"G\n\x13\x41mznScrapingRequest\x12\x19\n\x11request_timestamp\x18\x01 \x01(\x04\x12\x15\n\rproduct_codes\x18\x02 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTMESSAGE._serialized_start=34
  _TESTMESSAGE._serialized_end=64
  _AMZNSCRAPINGREQUEST._serialized_start=66
  _AMZNSCRAPINGREQUEST._serialized_end=137
# @@protoc_insertion_point(module_scope)
